import collections

messenger1 = '''QWHTGNBCMNPRDRGMAASLEDITQCFEQIGJSCFMZBWUSGQWEVVZAEPVUQZAEQAGBENYMJPOEVZVPQBNRTDRFWYYTJRTHJNYLQGRTPLBRFHZ
GSMCTCABDQGKCYGSIGCZWZPVNTSNEPIGGRPDFIYPCHJPIEGSYTLORFWYNRZRCHNVGQYYOCGPAGKBRJSMGJSCGSIGPOEVZVBTOYLYIGKC
YFZKBPQPVGMQCBOFZLRFWNNEMQEOYYZVTGBOHCMJGOCRXMGQBLTCMNVPLGETRHWPYOWSVVLGHIEYSSNGMPQAPGZLRFWNNEMNRCCGTWAQ
TEULBSKSWQLANHWYNWZRUHTARXYCQPSZZGJCDRHPBJSCRRIIGHSRTZYKJPFEPNVHSNEVNVWZAXQTJHWVGMVVWDNWBBISEUPZSKHEVYON
PRAEZXRTHSNEERUVZHWLQQHSVDJHVWYNWIEISCFPVFGKPPLVAQHOROQPCHPJPKNPBZGNWAUSNELBRYSNNYVBVVLYWWJVVTFRZBWBOGSM
OTOGRXMANWGVYONPRORLLJJCDGCCTIZPQSMEGVLIPKBPGPPCIGGRTGQIECPZIPWHTDZBCXBYSCGZIQFCCQPBECQEGSMJQFWQHQYNZTGE
TRPCERYWENCYTCMZGAMRCEUCHHRDILJSCRMCGKHNNYVRXSCSZZTGHHULBGJSJQTLUGFPVEQFHCCHDBUGZTITVTTOEUPZGQPPQPLVEOER
OPRTSEBEPRWBQVYQFJSOJZZXYVTPSBUGMHUZNBWUSGSMEGVLIPBUWGQNCABPCMYJIQXOYPPLVVWDELBUGFQBCCFVCMRSMEGRPQTKNVSO
GZBUGUCRLBGCGVEPUNKBTARJRHCCRFAGJOESCWZVVPFPPBPCCROLRCRHREIXGWYPCMNUSOQPDBVWZAEWGJOEPLCFGTZEHPVEVEUPGTCJ
PGSMYCGESFTYOSLFFZRQTORGWGKCYGSIGYSSRCMUKUSYJZRUCWIPBUCHEUPARFSLQDPNNZYBEPNXSOVPLVPJLVYBUCHEUTAACHTBYCAF
SCTZLFJOWYSIIGOYRHJVTHSBQNEGSOBXIAFHSNEOBXSCAXMAVCQGSMCGCAYPJLVVPCPWCNSQBCBUGDPBATRUVLYWVBVDPETAUHFZZEPR
GOCGS'''

messenger2 = '''FCNEROTBHTHNNWOCDBADEHPIAMETUWEGATLEGHAIATOEADAAGRROETIFWHODAONALFRNCTWRERSTAMLTTHTAOHSDIIREEOIWNNACT
OSNBMVNDTLREEEAVPOORAEDLENNEWEETNRETDRSSIRRDAETFHRCYOHAUSLAIAFTEDEHAKIBEAMERAACEOTTEHHVLUAOOTEHYLASDL
AEAASOESHNRFOTOMFEBPEHPATSMAOODNSUHRTHITTNNEIENIDEOOTECEAWEEGCWSWETONICINETNEEENATETAAMETROTDIEGEHHET
LTHTIIIOETNPAHDSNGNCTCEOSTAHWGDREIDWREECCDREOWADCWWINOGMHSRINFTTIEFTVATETRHIEKHWUEVSOYNTTOORIDETRNEUT
THEDKRDTOCFIEEALSFTHHIRVTESNVDITNNRHAETRMHVETOYEFELLPHTRURSYAREOFOSIAACINRDCTPSNANRDLENDRIATHRNNYOOVD
DELNWMATLLHRVEDETFFANSPFOOGHIHAIGVSGRIDETOOBAESADACTEENATRTANNDHUDHORIAOOEDETOITORRBAAETEOWHDIOHITODE
EENDWTHGREFNACIHRBECTGTEIFSFHODWEEDITAOCYTSLUDIAEGEETDHOEINTAUGAVWHEAAENHPTOOPELEFHTREEEGFRUONCNNTOVL
TDAORITLAEENAGIEVRIETAONNNESIDODEEGBEDAWETIAITISATLOSHAEVATOHEAEFNPRWUTULRENETACCWNLHOHVLGEOGHANATBUR
RDTTRLTTLEETYBCVRHEHTRENHBIDTUIWHHOHETAODESEUEDAORAMNOTRENDEIAEOHURHGHTMREOTRHSTHEATDNTHTNOLEBOENTRTE
LHPRESNRREHSAVAOASGRTOEEINEIYETTOTHLRAQORANAITNTHTRASCDOCCNUATRAFOTECOCPOHEALIAREEVIETNNTILTIGRTELHTA
SWNDENOREOLIUEEIAASGEVSTFORPTORHLLLEOMRWHUAEGAYEIULGEECHONSOIEFTHHRBVDRRSHETTESAGRHOSOETNSVNASWTAEFEE
VNWELOHEALHIVHIIDDLAIFDDGNOPEELTOHOIOE'''

count = collections.Counter(messenger1)
print('messenger nomers one most likely')
if count["E"] > 6 or count["T"] > 6 or count["A"] > 6 or count["O"] > 6 or count["I"] > 6 or count["N"] > 6:
    print('letters have changed their position')
if count["E"] <= 6 or count["T"] <= 6 or count["A"] <= 6 or count["O"] <= 6 or count["I"] <= 6 or count["N"] <= 6:
    print("Letters in the text are replaced")

count = collections.Counter(messenger2)
print('messenger nomers two most likely')
if count["E"] > 6 or count["T"] > 6 or count["A"] > 6 or count["O"] > 6 or count["I"] > 6 or count["N"] > 6:
    print('letters have changed their position')
if count["E"] <= 6 or count["T"] <= 6 or count["A"] <= 6 or count["O"] <= 6 or count["I"] <= 6 or count["N"] <= 6:
    print("Letters in the text are replaced")
